theme: cosmo

logo: https://github.com/sumeetmankar171/sumeetmankar171.github.io/blob/master/Images/circle-cropped.png?raw=true

title: SUMEET MANKAR

description:  PostDoctoral Research Fellow | Genomics and Phenomics Data Scientist | Donald Danforth Plant Science Center    

github: is\_project\_page:false
