theme: jekyll-theme-minimal

logo: https://github.com/sumeetmankar171/sumeetmankar171.github.io/blob/master/Images/imageedit_1_8050602042.png

title: Sumeet Mankar

description:  Plant Breeding | Texas A&M University    

github: is\_project\_page:false
