theme: theme: jekyll-theme-cayman

logo: https://github.com/sumeetmankar171/sumeetmankar171.github.io/blob/master/Images/circle-cropped.png?raw=true

title: SUMEET MANKAR

description:  PhD Candidate | Plant Breeding | Texas A&M University    

github: is\_project\_page:false
